name: post_builders
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  build: ^2.0.0
  build_runner: ^2.0.0
  build_runner_core: ^7.0.0
  source_gen: ^1.2.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
